# Generated by Django 5.1.1 on 2024-10-15 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengirim_object_id', models.PositiveIntegerField()),
                ('penerima_object_id', models.PositiveIntegerField()),
                ('isi_feedback', models.TextField(null=True)),
                ('tanggal', models.DateField(null=True)),
                ('penerima_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_penerima', to='contenttypes.contenttype')),
                ('pengirim_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_pengirim', to='contenttypes.contenttype')),
            ],
        ),
    ]
