# Generated by Django 5.1.1 on 2024-10-15 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wajib', models.CharField(choices=[('Ya', 'Ya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('id_matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.matakuliah')),
                ('id_mhs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.mahasiswa')),
            ],
        ),
    ]
