# Generated by Django 5.1.1 on 2024-10-15 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriKehadiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Alpa', 'Alpa'), ('Izin', 'Izin'), ('Sakit', 'Sakit')], max_length=20, null=True)),
                ('id_mhs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.mahasiswa')),
            ],
        ),
    ]
